// Zero questions after a CAD upload (src/autobind.js). A robot read from its CAD has
// exact joints but default mate names, so nothing says which joint "spinner" turns.
// The binder reads what any export has: a motor or servo part on a joint's axis, a
// pulley or gear on it, what the joint carries, and how the code uses each device
// (setVelocity is a flywheel, an encoder held to targets is an indexer, plain power
// a roller, a servo sent between two positions a flipper). It never reads this
// robot's names. The robot here is synthetic and generic: a chassis with four
// mecanum wheels and their hub bearings, an indexer on a belt, two flywheels with
// motors on their axles, an intake wheel on a belt, two mirrored servo flippers on
// servo splines, a hood servo, an odometry pod, and a crate of loose bearings.
import test from 'node:test';
import assert from 'node:assert/strict';
import { loadEngine } from './load.mjs';

const E = loadEngine();

const L = (name, size, kg, at = '0 0 0', rgba = '0.5 0.5 0.5 1') => `<link name="${name}"><inertial><mass value="${kg}"/></inertial><visual><origin xyz="${at}"/><geometry><box size="${size}"/></geometry><material name="m"><color rgba="${rgba}"/></material></visual></link>`;
const J = (name, type, parent, child, xyz, axis = '0 0 1', lim = null) => `<joint name="${name}" type="${type}"><origin xyz="${xyz}"/><parent link="${parent}"/><child link="${child}"/><axis xyz="${axis}"/>${lim ? `<limit effort="1" velocity="1" lower="${lim[0]}" upper="${lim[1]}"/>` : ''}</joint>`;
function robot() {
  let u = `<!--URDF generated by ONSHAPE BY PTC INC, 1.217-->\n<robot name="generic"><link name="root" />`;
  u += L('chassis_plate__1_', '0.40 0.36 0.01', 2.0) + J('fastened_0', 'fixed', 'root', 'chassis_plate__1_', '0 0 0.06');
  // four mecanum wheels on motors (5203), each with a hub bearing on its axle
  const corners = [[0.18, 0.17], [0.18, -0.17], [-0.18, 0.17], [-0.18, -0.17]];
  corners.forEach(([x, y], i) => {
    u += L(`mecanum_wheel_${i}__1_`, '0.10 0.04 0.10', 0.3) + J(`revolute_5${i}`, 'continuous', 'chassis_plate__1_', `mecanum_wheel_${i}__1_`, `${x} ${y} -0.01`, '0 1 0');
    u += L(`5203_series_yellow_jacket_motor_${i}__1_`, '0.04 0.09 0.04', 0.3, '0 0 0') + J(`fastened_m${i}`, 'fixed', 'chassis_plate__1_', `5203_series_yellow_jacket_motor_${i}__1_`, `${x} ${y * 0.65} -0.01`);
    u += L(`1611_bearing_${i}__1_`, '0.02 0.005 0.02', 0.004) + J(`revolute_6${i}`, 'continuous', 'chassis_plate__1_', `1611_bearing_${i}__1_`, `${x} ${y * 0.85} -0.01`, '0 1 0');
  });
  // the indexer: a heavy drum on a vertical axle with a big pulley, belt-driven from a motor elsewhere
  u += L('indexer_drum__1_', '0.30 0.30 0.10', 1.8, '0 0 0.05') + J('revolute_9', 'continuous', 'chassis_plate__1_', 'indexer_drum__1_', '0 0 0.12');
  u += L('htd_5mm_80t_pulley__1_', '0.12 0.12 0.01', 0.05) + J('fastened_p', 'fixed', 'indexer_drum__1_', 'htd_5mm_80t_pulley__1_', '0 0 -0.01');
  u += L('5203_series_yellow_jacket_motor_idx__1_', '0.04 0.04 0.09', 0.3) + J('fastened_mi', 'fixed', 'chassis_plate__1_', '5203_series_yellow_jacket_motor_idx__1_', '0.17 0.1 0.08');
  // two flywheels, high up, each on a motor's own axle
  for (const [k, y] of [[0, 0.06], [1, -0.06]]) {
    u += L(`flywheel_${k}__1_`, '0.096 0.03 0.096', 0.12) + J(`revolute_1${k}`, 'continuous', 'chassis_plate__1_', `flywheel_${k}__1_`, `-0.05 ${y} 0.32`, '0 1 0');
    u += L(`5203_series_yellow_jacket_motor_f${k}__1_`, '0.04 0.09 0.04', 0.3) + J(`fastened_mf${k}`, 'fixed', 'chassis_plate__1_', `5203_series_yellow_jacket_motor_f${k}__1_`, `-0.05 ${y * 2.2} 0.32`);
  }
  // the intake: a gripping wheel on a belt, up front
  u += L('3613_gripping_wheel__1_', '0.072 0.03 0.072', 0.06) + J('revolute_40', 'continuous', 'chassis_plate__1_', '3613_gripping_wheel__1_', '0.22 0 0.14', '0 1 0');
  u += L('htd_5mm_30t_pulley__1_', '0.03 0.01 0.03', 0.01) + J('fastened_ip', 'fixed', '3613_gripping_wheel__1_', 'htd_5mm_30t_pulley__1_', '0 0.02 0');
  // two mirrored flippers on servo splines, servos right at the pivots
  for (const [k, y] of [[0, 0.12], [1, -0.12]]) {
    u += L(`h25t_spline_hub_${k}__1_`, '0.015 0.01 0.015', 0.005) + J(`revolute_2${k}`, 'revolute', 'chassis_plate__1_', `h25t_spline_hub_${k}__1_`, `0.1 ${y} 0.2`, '0 1 0', [-0.3, 1.6]);
    u += L(`flipper_arm_${k}__1_`, '0.12 0.02 0.03', 0.08, '0.06 0 0') + J(`fastened_fa${k}`, 'fixed', `h25t_spline_hub_${k}__1_`, `flipper_arm_${k}__1_`, '0 0 0');
    u += L(`2000_0025_0002_servo_${k}__1_`, '0.04 0.02 0.04', 0.06) + J(`fastened_sv${k}`, 'fixed', 'chassis_plate__1_', `2000_0025_0002_servo_${k}__1_`, `0.1 ${y * 1.25} 0.2`);
  }
  // a hood on a servo
  u += L('h25t_spline_hub_h__1_', '0.015 0.01 0.015', 0.005) + J('revolute_30', 'revolute', 'chassis_plate__1_', 'h25t_spline_hub_h__1_', '-0.12 0 0.36', '0 1 0', [-0.5, 0.5]);
  u += L('hood__1_', '0.08 0.10 0.02', 0.05, '0.04 0 0') + J('fastened_hd', 'fixed', 'h25t_spline_hub_h__1_', 'hood__1_', '0 0 0');
  u += L('2000_0025_0003_servo_h__1_', '0.04 0.02 0.04', 0.06) + J('fastened_svh', 'fixed', 'chassis_plate__1_', '2000_0025_0003_servo_h__1_', '-0.12 0.03 0.36');
  // an odometry pod's swingarm on the chassis
  u += L('odometry_pod_swingarm__1_', '0.06 0.02 0.02', 0.02) + J('revolute_80', 'continuous', 'chassis_plate__1_', 'odometry_pod_swingarm__1_', '0 0.1 -0.03', '0 1 0');
  // a crate of loose bearings, each on its own axle
  for (let i = 0; i < 12; i++) u += L(`1611_0514_bearing_${i}__1_`, '0.014 0.005 0.014', 0.004) + J(`revolute_7${i}`, 'continuous', 'chassis_plate__1_', `1611_0514_bearing_${i}__1_`, `${-0.15 + 0.025 * i} -0.12 0.02`, '0 1 0');
  return u + '</robot>';
}
const CODE = `import com.qualcomm.robotcore.eventloop.opmode.*; import com.qualcomm.robotcore.hardware.*;
@TeleOp public class Generic extends LinearOpMode {
  DcMotorEx FL, FR, BL, BR, launcher, launcher2, feeder, indexer; Servo flipL, flipR, hood;
  public void runOpMode(){
    FL=hardwareMap.get(DcMotorEx.class,"FL"); FR=hardwareMap.get(DcMotorEx.class,"FR"); BL=hardwareMap.get(DcMotorEx.class,"BL"); BR=hardwareMap.get(DcMotorEx.class,"BR");
    launcher=hardwareMap.get(DcMotorEx.class,"launcher"); launcher2=hardwareMap.get(DcMotorEx.class,"launcher2"); feeder=hardwareMap.get(DcMotorEx.class,"feeder"); indexer=hardwareMap.get(DcMotorEx.class,"indexer");
    flipL=hardwareMap.servo.get("flipL"); flipR=hardwareMap.servo.get("flipR"); hood=hardwareMap.servo.get("hood");
    FL.setDirection(DcMotorSimple.Direction.REVERSE); BL.setDirection(DcMotorSimple.Direction.REVERSE);
    indexer.setMode(DcMotor.RunMode.STOP_AND_RESET_ENCODER); indexer.setMode(DcMotor.RunMode.RUN_WITHOUT_ENCODER);
    int target=0; waitForStart();
    while(opModeIsActive()){
      double y=-gamepad1.left_stick_y, x=gamepad1.left_stick_x, rx=gamepad1.right_stick_x;
      FL.setPower(y+x+rx); BL.setPower(y-x+rx); FR.setPower(y-x-rx); BR.setPower(y+x-rx);
      if(gamepad2.a) target+=2730;
      double err=target-indexer.getCurrentPosition(); indexer.setPower(Math.max(-0.4,Math.min(0.4,0.002*err)));
      if(gamepad2.right_trigger>0.1) feeder.setPower(1); else if(gamepad2.left_trigger>0.1) feeder.setPower(-1); else feeder.setPower(0);
      if(gamepad2.left_bumper){ launcher.setVelocity(1900); launcher2.setVelocity(1900); } else { launcher.setVelocity(0); launcher2.setVelocity(0); }
      if(gamepad2.dpad_up){ flipL.setPosition(0.4); flipR.setPosition(0.6); } else { flipL.setPosition(0.07); flipR.setPosition(0.93); }
      hood.setPosition(gamepad2.dpad_left?0.3:gamepad2.dpad_right?0.7:0.5);
    }
  }
}`;

test('autobind: every device finds its joint from the CAD and the code, with a reason, and the robot check has nothing to ask', () => {
  const cad = E.cadFromUrdf(robot(), {}, {});
  const code = E.parseJava(CODE);
  // the name mapper may already place a few by kind in a robot this small; the binder is what
  // the app runs after it, and it must leave nothing to ask whatever the mapper did
  const R = E.autoBind(cad, code, {}, {});
  const got = Object.fromEntries(R.picks.map((p) => [p.device, p.joint]));
  const viaMapper = E.autoBind(cad, code, E.autoMap(code.devices, cad.mechs, { cad }), {});
  for (const d of ['indexer', 'launcher', 'launcher2', 'feeder', 'flipL', 'flipR', 'hood']) assert.ok(viaMapper.map[d], d + ' is bound after the mapper too');
  assert.equal(got.indexer, 'indexer drum', 'the heaviest joint with a pulley, held to encoder targets: ' + JSON.stringify(got));
  assert.deepEqual([got.launcher, got.launcher2].sort(), ['flywheel 0', 'flywheel 1'], 'the two flywheels, a motor on each axle');
  assert.equal(got.feeder, '3613 gripping wheel', 'the gripping wheel on a belt');
  assert.deepEqual([got.flipL, got.flipR].sort(), ['flipper arm 0', 'flipper arm 1'], 'the mirrored servo flippers (each joint named for the arm it carries)');
  assert.equal(got.hood, 'hood', 'the hood servo');
  // never a bearing, a wheel hub, the odometry pod or a motor's own hub
  for (const p of R.picks) assert.ok(!/bearing|odometry|mecanum/.test(p.joint), p.device + ' -> ' + p.joint);
  // reasons a team can read
  const idx = R.picks.find((p) => p.device === 'indexer');
  assert.match(idx.why, /heaviest joint/); assert.match(idx.why, /encoder/);
  assert.match(R.picks.find((p) => p.device === 'launcher').why, /setVelocity/);
  // the robot check: no question left, the picks shown as notes with their reasons
  const RC = E.checkRobot(cad, code, R.map, { isCommanded: () => true, autoPicks: R.picks });
  assert.equal(RC.items.filter((i) => i.ask === 'pick-parts' || i.ask === 'pick-device').length, 0, RC.items.filter((i) => i.ask).map((i) => i.text).join(' | '));
  assert.ok(RC.items.some((i) => i.device === 'indexer' && i.sev === 'note' && /bound from the CAD/.test(i.text)));
  assert.equal(RC.need, 0);
});

test('autobind: a device with nothing in the CAD to go on stays unbound (and is still asked about); a STEP without mates gets no guesses', () => {
  const cad = E.cadFromUrdf(robot(), {}, {});
  const code = E.parseJava(CODE.replace('Servo flipL, flipR, hood;', 'Servo flipL, flipR, hood, mystery;').replace('hood=hardwareMap.servo.get("hood");', 'hood=hardwareMap.servo.get("hood"); mystery=hardwareMap.servo.get("mystery");')
    .replace('hood.setPosition(gamepad2.dpad_left?0.3:gamepad2.dpad_right?0.7:0.5);', 'hood.setPosition(gamepad2.dpad_left?0.3:gamepad2.dpad_right?0.7:0.5); mystery.setPosition(gamepad2.x?1:0);'));
  const R = E.autoBind(cad, code, E.autoMap(code.devices, cad.mechs, { cad }), {});
  assert.ok(!R.map.mystery, 'no fourth servo joint in the CAD: nothing to bind it to');
  assert.ok(R.ranked.mystery, 'what it would score is kept for the hardware table');
  const RC = E.checkRobot(cad, code, R.map, { isCommanded: () => true, autoPicks: R.picks });
  assert.equal(RC.items.filter((i) => i.ask === 'pick-parts').map((i) => i.device).join(), 'mystery');
  // no mates: nothing to stand on
  const step = { ...cad, mates: null };
  assert.deepEqual(E.autoBind(step, code, {}, {}).picks, []);
});
