/* ============================================================
   URDF → THE SAME ROBOT AN ONSHAPE IMPORT GIVES
   ------------------------------------------------------------
   Teams on Fusion, SolidWorks or FreeCAD can export URDF (fusion2urdf,
   ACDC4Robot, sw_urdf_exporter, FreeCAD's CROSS), and Onshape exports it
   natively (right-click the assembly tab → Export → URDF): the robot's
   links and its joints, with axes, limits, masses, colours and meshes.
   That is the same information an Onshape assembly holds, so it is
   translated into the bookmark's payload (src/onshapecad.js): each link
   is a part, each joint a mate between them, a mimic joint a mate
   relation. One builder then makes the robot either way.

   Onshape's own export (header "URDF generated by ONSHAPE BY PTC") has
   its own habits, all read here: a shapeless "root" link as the base,
   one link per part instance with names lowercased and underscored,
   fastened mates as fixed joints, mates with no limits as continuous
   joints, a mate that closes a linkage loop as a joint to a dummy link
   named "<part>__1__loop_closure", a cylindrical mate as a slide and a
   turn through a dummy link, a planar mate as dummies too, gear
   relations as <mimic>, and near-zero masses for parts with no material.

   Meshes: STL (binary or ASCII), OBJ, glTF and GLB (buffers embedded or
   beside the file), and COLLADA (.dae), dropped or zipped with the .urdf
   (src/zipin.js) and matched by file name. Box, cylinder and sphere
   visuals are built here. Xacro must be expanded first.
   ============================================================ */
/* A small XML reader: elements, attributes, self-closing tags, and the text
   inside an element (COLLADA keeps its numbers there). Enough for URDF. */
function urdfXml(text){
  const root={tag:"#root",attrs:{},kids:[]}, stack=[root];
  const re=/<!--[\s\S]*?-->|<\?[\s\S]*?\?>|<!\[CDATA\[[\s\S]*?\]\]>|<!DOCTYPE[^>]*>|<\/\s*([\w:.-]+)\s*>|<\s*([\w:.-]+)((?:\s+[\w:.-]+\s*=\s*(?:"[^"]*"|'[^']*'))*)\s*(\/?)>/g;
  let m, last=0;
  while((m=re.exec(text))){
    const gap=text.slice(last,m.index); last=re.lastIndex;
    if(gap&&/\S/.test(gap)){ const top=stack[stack.length-1]; top.text=(top.text||"")+gap; }
    if(m[1]){ const close=m[1].replace(/^.*:/,""); while(stack.length>1&&stack.pop().tag!==close); continue; }
    if(!m[2]) continue;
    const attrs={}, ra=/([\w:.-]+)\s*=\s*("([^"]*)"|'([^']*)')/g; let a;
    while((a=ra.exec(m[3]||""))) attrs[a[1]]=(a[3]!=null?a[3]:a[4]).replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&");
    const el={tag:m[2].replace(/^.*:/,""),attrs,kids:[]};
    stack[stack.length-1].kids.push(el);
    if(!m[4]) stack.push(el);
  }
  return root;
}
const urdfKid=(el,tag)=>el&&el.kids.find(k=>k.tag===tag)||null;
const urdfKids=(el,tag)=>el?el.kids.filter(k=>k.tag===tag):[];
const urdfNums=(s,n,d)=>{ const v=String(s==null?"":s).trim().split(/\s+/).map(Number); return v.length>=n&&v.slice(0,n).every(Number.isFinite)?v.slice(0,n):d; };
const urdfFloats=s=>String(s||"").trim().split(/\s+/).filter(Boolean).map(Number);

/* 4x4 transforms as {r:[3][3], t:[3]} */
function urdfRpy(rpy){
  const [r,p,y]=rpy, cr=Math.cos(r), sr=Math.sin(r), cp=Math.cos(p), sp=Math.sin(p), cy=Math.cos(y), sy=Math.sin(y);
  return [[cy*cp, cy*sp*sr-sy*cr, cy*sp*cr+sy*sr],[sy*cp, sy*sp*sr+cy*cr, sy*sp*cr-cy*sr],[-sp, cp*sr, cp*cr]];
}
function urdfOrigin(el){
  const o=urdfKid(el,"origin");
  return {r:urdfRpy(urdfNums(o&&o.attrs.rpy,3,[0,0,0])), t:urdfNums(o&&o.attrs.xyz,3,[0,0,0])};
}
const urdfMul=(A,B)=>({r:A.r.map(row=>[0,1,2].map(j=>row[0]*B.r[0][j]+row[1]*B.r[1][j]+row[2]*B.r[2][j])),
  t:[0,1,2].map(i=>A.r[i][0]*B.t[0]+A.r[i][1]*B.t[1]+A.r[i][2]*B.t[2]+A.t[i])});
const urdfInv=A=>{ const R=[[A.r[0][0],A.r[1][0],A.r[2][0]],[A.r[0][1],A.r[1][1],A.r[2][1]],[A.r[0][2],A.r[1][2],A.r[2][2]]];
  return {r:R, t:[0,1,2].map(i=>-(R[i][0]*A.t[0]+R[i][1]*A.t[1]+R[i][2]*A.t[2]))}; };
const urdfPt=(A,p)=>[0,1,2].map(i=>A.r[i][0]*p[0]+A.r[i][1]*p[1]+A.r[i][2]*p[2]+A.t[i]);
const urdfDir=(A,v)=>[0,1,2].map(i=>A.r[i][0]*v[0]+A.r[i][1]*v[1]+A.r[i][2]*v[2]);
const urdfT16=A=>[A.r[0][0],A.r[0][1],A.r[0][2],A.t[0], A.r[1][0],A.r[1][1],A.r[1][2],A.t[1], A.r[2][0],A.r[2][1],A.r[2][2],A.t[2], 0,0,0,1];
/* a 4x4 given as 16 numbers, row-major, as {r,t} */
const urdfFrom16=M=>({r:[[M[0],M[1],M[2]],[M[4],M[5],M[6]],[M[8],M[9],M[10]]], t:[M[3],M[7],M[11]]});

/* ---- meshes: each reader gives flat xyz triples in the file's own frame ---- */
const urdfU8=buf=>buf instanceof Uint8Array?buf:new Uint8Array(buf);
const urdfDecode=s=>{ try{ return decodeURIComponent(s); }catch(e){ return s; } };
const urdfText=buf=>typeof buf==="string"?buf:new TextDecoder().decode(urdfU8(buf));
/* STL, binary or ASCII */
function urdfStl(buf){
  const u8=urdfU8(buf);
  const head=String.fromCharCode.apply(null,u8.subarray(0,Math.min(512,u8.length)));
  const dv=new DataView(u8.buffer,u8.byteOffset,u8.byteLength);
  const n=u8.length>=84?dv.getUint32(80,true):0;
  // binary: the size says so exactly (an ASCII header can still start with "solid")
  if(u8.length>=84&&u8.length===84+n*50){
    const out=new Array(n*9);
    for(let i=0;i<n;i++){ const o=84+i*50+12; for(let k=0;k<9;k++) out[i*9+k]=dv.getFloat32(o+k*4,true); }
    return out;
  }
  const text=typeof TextDecoder==="function"?new TextDecoder().decode(u8):head;
  const out=[], re=/vertex\s+([-+\d.eE]+)\s+([-+\d.eE]+)\s+([-+\d.eE]+)/g; let m;
  while((m=re.exec(text))) out.push(+m[1],+m[2],+m[3]);
  return out.length%9?out.slice(0,out.length-out.length%9):out;
}
/* Wavefront OBJ: v and f lines; polygons fanned into triangles; negative indices count back */
function urdfObj(buf){
  const text=urdfText(buf), V=[], out=[];
  const lines=text.split(/\r?\n/);
  for(const line of lines){
    if(line.charCodeAt(0)===118&&line.charCodeAt(1)===32){        // "v "
      const p=line.trim().split(/\s+/); if(p.length>=4) V.push([+p[1],+p[2],+p[3]]);
    }else if(line.charCodeAt(0)===102&&(line.charCodeAt(1)===32||line.charCodeAt(1)===9)){   // "f "
      const idx=line.trim().split(/\s+/).slice(1).map(t=>{ const i=parseInt(t.split("/")[0],10); return i<0?V.length+i:i-1; }).filter(i=>i>=0&&i<V.length);
      for(let k=1;k+1<idx.length;k++){ const a=V[idx[0]], b=V[idx[k]], c=V[idx[k+1]]; out.push(a[0],a[1],a[2],b[0],b[1],b[2],c[0],c[1],c[2]); }
    }
  }
  return out;
}
/* glTF 2.0, as text (.gltf, buffers embedded as data: URIs or in files beside
   it) or binary (.glb): every node's meshes, placed by the node tree, as
   {name, tri, color, parents} per mesh node, for a part made of several. */
function urdfGltfScene(buf,files){
  const u8=urdfU8(buf), dv=new DataView(u8.buffer,u8.byteOffset,u8.byteLength);
  let json, bin=null;
  if(u8.length>=20&&dv.getUint32(0,true)===0x46546C67){
    const jl=dv.getUint32(12,true); json=JSON.parse(new TextDecoder().decode(u8.subarray(20,20+jl)));
    const bp=20+jl; if(bp+8<=u8.length&&dv.getUint32(bp+4,true)===0x004E4942){ const bl=dv.getUint32(bp,true); bin=u8.subarray(bp+8,Math.min(u8.length,bp+8+bl)); }
  }else json=JSON.parse(urdfText(u8));
  const base=s=>String(s||"").replace(/^.*[\\/]/,"").toLowerCase();
  const lower=Object.create(null); for(const k in files||{}) lower[base(k)]=files[k];
  const buffers=(json.buffers||[]).map(b=>{
    if(b.uri&&/^data:/i.test(b.uri)){ const s=atob(b.uri.slice(b.uri.indexOf(",")+1)); const o=new Uint8Array(s.length); for(let i=0;i<s.length;i++) o[i]=s.charCodeAt(i); return o; }
    if(b.uri){ const f=lower[base(urdfDecode(b.uri))]||lower[base(b.uri)]; if(!f) throw new Error("the glTF's buffer "+base(b.uri)+" isn't with it"); return urdfU8(f); }
    if(bin) return bin; throw new Error("a glTF buffer has no data");
  });
  const SIZE={5120:1,5121:1,5122:2,5123:2,5125:4,5126:4}, N={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT4:16};
  const acc=i=>{
    const a=(json.accessors||[])[i], v=a&&(json.bufferViews||[])[a.bufferView], B=v&&buffers[v.buffer], n=a&&N[a.type], sz=a&&SIZE[a.componentType];
    if(!a||!v||!B||!n||!sz||!Number.isInteger(a.count)||a.count<0) throw new Error("a glTF accessor is broken");
    const stride=v.byteStride||sz*n, start=(v.byteOffset||0)+(a.byteOffset||0);
    const d=new DataView(B.buffer,B.byteOffset,B.byteLength);
    if(a.count&&start+(a.count-1)*stride+sz*n>d.byteLength) throw new Error("a glTF accessor points past its buffer");
    const out=new Float64Array(a.count*n);
    const get=o=>a.componentType===5126?d.getFloat32(o,true):a.componentType===5125?d.getUint32(o,true):a.componentType===5123?d.getUint16(o,true):a.componentType===5121?d.getUint8(o)
      :a.componentType===5122?d.getInt16(o,true):d.getInt8(o);
    for(let k=0;k<a.count;k++) for(let c=0;c<n;c++) out[k*n+c]=get(start+k*stride+c*sz);
    return out;
  };
  const I4=[1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1];
  const mul=(A,B)=>{ const o=new Array(16); for(let r=0;r<4;r++) for(let c=0;c<4;c++){ let s=0; for(let k=0;k<4;k++) s+=A[4*r+k]*B[4*k+c]; o[4*r+c]=s; } return o; };
  const trs=(t,q,s)=>{ const [x,y,z,w]=q||[0,0,0,1], S=s||[1,1,1], T=t||[0,0,0];
    return [(1-2*(y*y+z*z))*S[0],2*(x*y-z*w)*S[1],2*(x*z+y*w)*S[2],T[0], 2*(x*y+z*w)*S[0],(1-2*(x*x+z*z))*S[1],2*(y*z-x*w)*S[2],T[1],
            2*(x*z-y*w)*S[0],2*(y*z+x*w)*S[1],(1-2*(x*x+y*y))*S[2],T[2], 0,0,0,1]; };
  const local=n=>Array.isArray(n.matrix)&&n.matrix.length===16?[n.matrix[0],n.matrix[4],n.matrix[8],n.matrix[12], n.matrix[1],n.matrix[5],n.matrix[9],n.matrix[13], n.matrix[2],n.matrix[6],n.matrix[10],n.matrix[14], n.matrix[3],n.matrix[7],n.matrix[11],n.matrix[15]]
    :trs(n.translation,n.rotation,n.scale);
  const nodes=json.nodes||[], out=[];
  const color=mi=>{ const m=json.materials&&json.materials[mi], f=m&&m.pbrMetallicRoughness&&m.pbrMetallicRoughness.baseColorFactor; return Array.isArray(f)&&f.length>=3?f.slice(0,3).map(Number):null; };
  const seen=new Set();
  const walk=(ni,P,parents,depth)=>{
    if(depth>32||seen.has(ni)) return; seen.add(ni);
    const n=nodes[ni]||{}, W=mul(P,local(n)), names=parents.concat([n.name||""]);
    if(Number.isInteger(n.mesh)&&json.meshes[n.mesh]){
      const tri=[]; let col=null;
      for(const p of json.meshes[n.mesh].primitives||[]){
        if(p.mode!=null&&p.mode!==4&&p.mode!==5&&p.mode!==6) continue;
        if(!p.attributes||!Number.isInteger(p.attributes.POSITION)) continue;
        const pos=acc(p.attributes.POSITION), idx=Number.isInteger(p.indices)?acc(p.indices):null, nv=pos.length/3;
        if(col==null&&Number.isInteger(p.material)) col=color(p.material);
        const at=k=>{ const q=3*k, x=pos[q], y=pos[q+1], z=pos[q+2]; return [W[0]*x+W[1]*y+W[2]*z+W[3], W[4]*x+W[5]*y+W[6]*z+W[7], W[8]*x+W[9]*y+W[10]*z+W[11]]; };
        const push=(a,b,c)=>{ if(a>=nv||b>=nv||c>=nv) return; const A=at(a),B=at(b),C=at(c); tri.push(A[0],A[1],A[2],B[0],B[1],B[2],C[0],C[1],C[2]); };
        const n3=idx?idx.length:nv, ix=k=>idx?idx[k]:k;
        if(p.mode==null||p.mode===4) for(let k=0;k+2<n3;k+=3) push(ix(k),ix(k+1),ix(k+2));
        else if(p.mode===5) for(let k=0;k+2<n3;k++) k%2?push(ix(k+1),ix(k),ix(k+2)):push(ix(k),ix(k+1),ix(k+2));
        else for(let k=1;k+1<n3;k++) push(ix(0),ix(k),ix(k+1));
      }
      if(tri.length) out.push({name:n.name||"", tri, color:col, parents:names});
    }
    for(const c of n.children||[]) walk(c,W,names,depth+1);
  };
  const roots=json.scenes&&json.scenes[json.scene||0]?json.scenes[json.scene||0].nodes||[]:nodes.map((_,i)=>i).filter(i=>!nodes.some(n=>(n.children||[]).includes(i)));
  for(const r of roots) walk(r,I4,[],0);
  out.generator=String(json.asset&&json.asset.generator||"");
  return out;
}
function urdfGltf(buf,files){ const out=[]; for(const m of urdfGltfScene(buf,files)) for(const v of m.tri) out.push(v); return out; }
/* COLLADA (.dae), as fusion2urdf and FreeCAD write it: the geometries, placed by
   the visual scene's nodes, in metres, Z up. */
function urdfDae(buf){
  const doc=urdfXml(urdfText(buf)), col=doc.kids.find(k=>k.tag==="COLLADA"); if(!col) throw new Error("not a COLLADA file");
  const asset=urdfKid(col,"asset"), unit=asset&&urdfKid(asset,"unit"), meter=unit&&+unit.attrs.meter>0?+unit.attrs.meter:1;
  const up=((asset&&urdfKid(asset,"up_axis")||{}).text||"Y_UP").trim();
  const geoms=new Map();
  for(const lib of urdfKids(col,"library_geometries")) for(const g of urdfKids(lib,"geometry")){
    const mesh=urdfKid(g,"mesh"); if(!mesh) continue;
    const src=new Map(); for(const s of urdfKids(mesh,"source")){ const fa=urdfKid(s,"float_array"); if(fa) src.set("#"+s.attrs.id,urdfFloats(fa.text)); }
    const verts=new Map(); for(const v of urdfKids(mesh,"vertices")){ const inp=urdfKids(v,"input").find(i=>i.attrs.semantic==="POSITION"); if(inp) verts.set("#"+v.attrs.id,src.get(inp.attrs.source)); }
    const tri=[];
    for(const prim of mesh.kids){
      if(!/^(triangles|polylist|polygons)$/.test(prim.tag)) continue;
      const inputs=urdfKids(prim,"input"), vin=inputs.find(i=>i.attrs.semantic==="VERTEX"); if(!vin) continue;
      const P=verts.get(vin.attrs.source)||src.get(vin.attrs.source); if(!P) continue;
      const stride=Math.max(...inputs.map(i=>(+i.attrs.offset||0)+1)), off=+vin.attrs.offset||0;
      const pt=i=>[P[3*i],P[3*i+1],P[3*i+2]];
      const polys=[];
      if(prim.tag==="polylist"){ const vc=urdfFloats((urdfKid(prim,"vcount")||{}).text), p=urdfFloats((urdfKid(prim,"p")||{}).text); let at=0;
        for(const n of vc){ const poly=[]; for(let k=0;k<n;k++){ poly.push(p[(at+k)*stride+off]); } at+=n; polys.push(poly); } }
      else if(prim.tag==="polygons"){ for(const pe of urdfKids(prim,"p")){ const p=urdfFloats(pe.text), poly=[]; for(let k=0;k*stride<p.length;k++) poly.push(p[k*stride+off]); polys.push(poly); } }
      else { const p=urdfFloats((urdfKid(prim,"p")||{}).text); for(let k=0;(k+2)*stride<=p.length;k+=3) polys.push([p[k*stride+off],p[(k+1)*stride+off],p[(k+2)*stride+off]]); }
      for(const poly of polys) for(let k=1;k+1<poly.length;k++){ const a=pt(poly[0]), b=pt(poly[k]), c=pt(poly[k+1]); if([a,b,c].every(q=>q.every(Number.isFinite))) tri.push(...a,...b,...c); }
    }
    if(tri.length) geoms.set("#"+g.attrs.id,tri);
  }
  // where the scene puts each geometry; one never placed sits at the origin
  const placed=new Set(), out=[];
  const rad=d=>d*Math.PI/180;
  const place=(tri,M)=>{ for(let k=0;k<tri.length;k+=3){ const x=tri[k],y=tri[k+1],z=tri[k+2]; out.push(M[0]*x+M[1]*y+M[2]*z+M[3], M[4]*x+M[5]*y+M[6]*z+M[7], M[8]*x+M[9]*y+M[10]*z+M[11]); } };
  const mul=(A,B)=>{ const o=new Array(16); for(let r=0;r<4;r++) for(let c=0;c<4;c++){ let s=0; for(let k=0;k<4;k++) s+=A[4*r+k]*B[4*k+c]; o[4*r+c]=s; } return o; };
  const walk=(node,P,depth)=>{
    if(depth>32) return;
    let M=P;
    for(const k of node.kids){
      if(k.tag==="matrix"){ const v=urdfFloats(k.text); if(v.length===16) M=mul(M,v); }
      else if(k.tag==="translate"){ const v=urdfFloats(k.text); if(v.length===3) M=mul(M,[1,0,0,v[0],0,1,0,v[1],0,0,1,v[2],0,0,0,1]); }
      else if(k.tag==="scale"){ const v=urdfFloats(k.text); if(v.length===3) M=mul(M,[v[0],0,0,0,0,v[1],0,0,0,0,v[2],0,0,0,0,1]); }
      else if(k.tag==="rotate"){ const v=urdfFloats(k.text); if(v.length===4){ const [x,y,z]=v, t=rad(v[3]), c=Math.cos(t), s=Math.sin(t), C=1-c, n=Math.hypot(x,y,z)||1, a=x/n,b=y/n,d=z/n;
        M=mul(M,[c+a*a*C,a*b*C-d*s,a*d*C+b*s,0, b*a*C+d*s,c+b*b*C,b*d*C-a*s,0, d*a*C-b*s,d*b*C+a*s,c+d*d*C,0, 0,0,0,1]); } }
    }
    for(const ig of urdfKids(node,"instance_geometry")){ const g=geoms.get(ig.attrs.url); if(g){ placed.add(ig.attrs.url); place(g,M); } }
    for(const c of urdfKids(node,"node")) walk(c,M,depth+1);
  };
  for(const lib of urdfKids(col,"library_visual_scenes")) for(const vs of urdfKids(lib,"visual_scene")) for(const n of urdfKids(vs,"node")) walk(n,[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],0);
  for(const [id,g] of geoms) if(!placed.has(id)) place(g,[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);
  // the file's unit and up axis, to metres with Z up
  for(let k=0;k<out.length;k+=3){
    let x=out[k]*meter, y=out[k+1]*meter, z=out[k+2]*meter;
    if(/^Y_UP$/i.test(up)){ const t=y; y=-z; z=t; } else if(/^X_UP$/i.test(up)){ const t=x; x=-z; z=t; }
    out[k]=x; out[k+1]=y; out[k+2]=z;
  }
  return out;
}
/* Any mesh a URDF or MJCF may name, by its extension; null for one that can't be read */
function urdfMesh(fname,buf,files){
  const ext=(/\.([a-z0-9]+)$/i.exec(String(fname||""))||[,""])[1].toLowerCase();
  if(ext==="stl") return urdfStl(buf);
  if(ext==="obj") return urdfObj(buf);
  if(ext==="gltf"||ext==="glb") return urdfGltf(buf,files);
  if(ext==="dae") return urdfDae(buf);
  return null;
}
const URDF_MESH_EXT=/\.(stl|obj|gltf|glb|dae)$/i;
/* box, cylinder (along z), sphere: triangles in the visual's own frame */
function urdfPrim(g){
  const T=[], push=(a,b,c)=>T.push(a[0],a[1],a[2],b[0],b[1],b[2],c[0],c[1],c[2]);
  if(g.tag==="box"){
    const [x,y,z]=urdfNums(g.attrs.size,3,[0.01,0.01,0.01]).map(v=>v/2);
    const V=[[-x,-y,-z],[x,-y,-z],[x,y,-z],[-x,y,-z],[-x,-y,z],[x,-y,z],[x,y,z],[-x,y,z]];
    for(const [a,b,c,d] of [[0,3,2,1],[4,5,6,7],[0,1,5,4],[1,2,6,5],[2,3,7,6],[3,0,4,7]]){ push(V[a],V[b],V[c]); push(V[a],V[c],V[d]); }
  } else if(g.tag==="cylinder"){
    const r=+g.attrs.radius||0.01, h=(+g.attrs.length||0.01)/2, N=24;
    for(let i=0;i<N;i++){ const a=2*Math.PI*i/N, b=2*Math.PI*(i+1)/N, A=[r*Math.cos(a),r*Math.sin(a)], B=[r*Math.cos(b),r*Math.sin(b)];
      push([0,0,-h],[B[0],B[1],-h],[A[0],A[1],-h]); push([0,0,h],[A[0],A[1],h],[B[0],B[1],h]);
      push([A[0],A[1],-h],[B[0],B[1],-h],[B[0],B[1],h]); push([A[0],A[1],-h],[B[0],B[1],h],[A[0],A[1],h]); }
  } else if(g.tag==="sphere"){
    const r=+g.attrs.radius||0.01, N=12, M=8, P=(i,j)=>{ const t=Math.PI*j/M, f=2*Math.PI*i/N; return [r*Math.sin(t)*Math.cos(f),r*Math.sin(t)*Math.sin(f),r*Math.cos(t)]; };
    for(let i=0;i<N;i++) for(let j=0;j<M;j++){ push(P(i,j),P(i,j+1),P(i+1,j+1)); push(P(i,j),P(i+1,j+1),P(i+1,j)); }
  }
  return T;
}
/* Fewer triangles for a dense mesh (Onshape's STL of a channel with forty holes runs
   to tens of thousands): every vertex snaps to a grid cell and the cell's vertices
   merge into their mean, so flat faces collapse to a few triangles and small holes
   close. The grid is coarsened until the mesh fits the budget. The result is a
   Float32Array: half the memory of a plain array, and what the view uploads. */
function urdfDecimate(T,budget){
  const n=T.length/9;
  if(n<=budget) return T instanceof Float32Array?T:Float32Array.from(T);
  const mn=[Infinity,Infinity,Infinity], mx=[-Infinity,-Infinity,-Infinity];
  for(let k=0;k<T.length;k+=3) for(let q=0;q<3;q++){ const v=T[k+q]; if(v<mn[q]) mn[q]=v; if(v>mx[q]) mx[q]=v; }
  const span=Math.max(mx[0]-mn[0],mx[1]-mn[1],mx[2]-mn[2])||1;
  // start fine (a 2.5 mm grid on a 400 mm channel) and coarsen only as far as the budget needs
  let cells=160, best=null;
  for(let pass=0;pass<18;pass++){
    const C=cells+1, cell=span/cells, rep=new Map(), sum=[], idx=new Int32Array(T.length/3);
    for(let v=0;v<idx.length;v++){
      const x=T[3*v], y=T[3*v+1], z=T[3*v+2];
      const key=Math.floor((x-mn[0])/cell)+(Math.floor((y-mn[1])/cell)+Math.floor((z-mn[2])/cell)*C)*C;
      let r=rep.get(key); if(r==null){ r=sum.length; rep.set(key,r); sum.push([0,0,0,0]); }
      const s=sum[r]; s[0]+=x; s[1]+=y; s[2]+=z; s[3]++; idx[v]=r;
    }
    let kept=0; for(let f=0;f<n;f++){ const a=idx[3*f], b=idx[3*f+1], c=idx[3*f+2]; if(a!==b&&b!==c&&a!==c) kept++; }
    const out=new Float32Array(kept*9); let o=0;
    for(let f=0;f<n;f++){ const a=idx[3*f], b=idx[3*f+1], c=idx[3*f+2]; if(a===b||b===c||a===c) continue;
      for(const r of [a,b,c]){ const s=sum[r]; out[o++]=s[0]/s[3]; out[o++]=s[1]/s[3]; out[o++]=s[2]/s[3]; } }
    best=out;
    if(kept<=budget||cells<=4) break;
    cells=Math.max(4,Math.floor(cells*0.85));
  }
  return best;
}
/* a mesh scaled and placed by a visual's origin, as a Float32Array */
function urdfPlace(T,O,sc){
  const out=new Float32Array(T.length), r=O.r, t=O.t, s=sc||[1,1,1];
  for(let k=0;k<T.length;k+=3){ const x=T[k]*s[0], y=T[k+1]*s[1], z=T[k+2]*s[2];
    out[k]=r[0][0]*x+r[0][1]*y+r[0][2]*z+t[0]; out[k+1]=r[1][0]*x+r[1][1]*y+r[1][2]*z+t[1]; out[k+2]=r[2][0]*x+r[2][1]*y+r[2][2]*z+t[2]; }
  return out;
}
/* How many triangles a mesh holds, without reading it: the STL header, the OBJ's
   face lines, the glTF's accessors. Null when it would take a full read (DAE). */
function urdfMeshCount(fname,buf){
  const ext=(/\.([a-z0-9]+)$/i.exec(String(fname||""))||[,""])[1].toLowerCase(), u8=urdfU8(buf);
  if(ext==="stl"){
    if(u8.length>=84){ const n=new DataView(u8.buffer,u8.byteOffset,u8.byteLength).getUint32(80,true); if(u8.length===84+n*50) return n; }
    const t=urdfText(u8); let n=0, i=-1; while((i=t.indexOf("facet normal",i+1))>=0) n++; return n;
  }
  if(ext==="obj"){ const t=urdfText(u8); let n=0; for(const line of t.split(/\r?\n/)) if(line.charCodeAt(0)===102&&(line.charCodeAt(1)===32||line.charCodeAt(1)===9)){ const k=line.trim().split(/\s+/).length-1; n+=Math.max(1,k-2); } return n; }
  if(ext==="gltf"||ext==="glb"){
    try{
      const dv=new DataView(u8.buffer,u8.byteOffset,u8.byteLength);
      const json=dv.getUint32(0,true)===0x46546C67?JSON.parse(new TextDecoder().decode(u8.subarray(20,20+dv.getUint32(12,true)))):JSON.parse(urdfText(u8));
      let n=0; for(const m of json.meshes||[]) for(const p of m.primitives||[]){ const a=json.accessors[Number.isInteger(p.indices)?p.indices:(p.attributes||{}).POSITION]; if(a) n+=Math.floor(a.count/3); }
      return n;
    }catch(e){ return null; }
  }
  return null;
}
/* a closed mesh's volume (the divergence theorem over its triangles), in the mesh's units */
function urdfVolume(T){
  let v=0;
  for(let k=0;k<T.length;k+=9){ const ax=T[k],ay=T[k+1],az=T[k+2], bx=T[k+3],by=T[k+4],bz=T[k+5], cx=T[k+6],cy=T[k+7],cz=T[k+8];
    v+=ax*(by*cz-bz*cy)+ay*(bz*cx-bx*cz)+az*(bx*cy-by*cx); }
  return Math.abs(v)/6;
}
/* A part with no material in Onshape is exported with a density of 1 kg/m³ (its
   "mass" is its volume in m³). Its real mass is its volume times what it's made
   of: aluminium unless the name or part number says steel, plastic, rubber, a motor. */
const URDF_DENSITY={fastener:7850, motor:2000, servo:1500, wheel:1100, electronics:1200, clear:1200, printed:500, belt:1200, metal:2700};
function urdfDensity(name,pn){ const k=typeof solidKind==="function"?solidKind(name,pn):"metal"; return URDF_DENSITY[k]||URDF_DENSITY.metal; }
/* How many triangles a part may keep: a whole robot stays near a million placed
   triangles, which a Chromebook's tab and GPU carry; one part never below 600. */
function urdfTriBudget(meshLinks,total){ return Math.max(600,Math.min(5000,Math.round((total||1.2e6)/Math.max(1,meshLinks)))); }
/* a short stable hash of a string, for geometry keys */
function urdfHash(s){ let h=0x811c9dc5; for(let i=0;i<s.length;i++){ h^=s.charCodeAt(i); h=Math.imul(h,16777619)>>>0; } return h.toString(36); }
/* Onshape's URDF names a part by its instance, lowercased, every other character an
   underscore: "20 Gripper Assembly <1>" -> "20_gripper_assembly__1_". Back to words,
   and the goBILDA / REV part number out of it. */
function urdfPartNumber(name){
  const s=String(name||"");
  const g=/(\d{4})[-_](\d{4})[-_](\d{1,4})(?!\d)/.exec(s); if(g) return g[1]+"-"+g[2]+"-"+g[3];
  const r=/(?:^|[^a-z0-9])rev[-_](\d{2})[-_](\d{4})(?!\d)/i.exec(s); if(r) return "REV-"+r[1]+"-"+r[2];
  return null;
}
function urdfPrettyName(name){
  return String(name||"").replace(/__(\d+)_(?=_|$)/g," <$1>").replace(/_+/g," ").replace(/\s+/g," ").trim();
}

/* The URDF as a SimBench robot payload. files: {name or basename: ArrayBuffer} for meshes. */
function urdfToPayload(text,files,name,opts){
  files=files||{}; opts=opts||{};
  const doc=urdfXml(text), robot=doc.kids.find(k=>k.tag==="robot");
  if(!robot) throw new Error("no <robot> in this file"+(/xacro/.test(text)?" (it's a xacro file: run xacro on it first)":""));
  if(/<xacro:|\$\{/.test(text)) throw new Error("this is a xacro file; run xacro on it first to get the plain URDF");
  const onshape=/generated by ONSHAPE/i.test(text.slice(0,400));
  const materials={};
  for(const m of urdfKids(robot,"material")){ const c=urdfKid(m,"color"); if(c&&m.attrs.name) materials[m.attrs.name]=urdfNums(c.attrs.rgba,3,null); }
  const links=urdfKids(robot,"link"), joints=urdfKids(robot,"joint");
  if(!links.length) throw new Error("the URDF has no links");
  const childOf=new Set(joints.map(j=>(urdfKid(j,"child")||{attrs:{}}).attrs.link));
  const root=links.find(l=>!childOf.has(l.attrs.name))||links[0];
  const byName=new Map(links.map(l=>[l.attrs.name,l]));
  const notes=[];
  // where each link sits with every joint at zero
  const W=new Map([[root.attrs.name,{r:[[1,0,0],[0,1,0],[0,0,1]],t:[0,0,0]}]]);
  const jOf=new Map();
  for(let pass=0;pass<links.length+2;pass++) for(const j of joints){
    const p=(urdfKid(j,"parent")||{attrs:{}}).attrs.link, c=(urdfKid(j,"child")||{attrs:{}}).attrs.link;
    if(!W.has(p)||W.has(c)) continue;
    W.set(c,urdfMul(W.get(p),urdfOrigin(j))); jOf.set(c,j);
  }
  const unplaced=links.filter(l=>!W.has(l.attrs.name)).map(l=>l.attrs.name||"?");
  if(unplaced.length) notes.push(unplaced.length+" link"+(unplaced.length===1?" hangs":"s hang")+" from a joint whose parent isn't in the file, so "+(unplaced.length===1?"it's":"they're")+" left out: "+unplaced.slice(0,5).join(", ")+(unplaced.length>5?" …":""));
  const missingMesh=new Set(), base=s=>String(s||"").replace(/^.*[\\/]/,"").toLowerCase();
  // the files by their whole path (lowercased, forward slashes) and by bare name
  const norm=s=>String(s||"").replace(/\\/g,"/").toLowerCase();
  const fileByPath=Object.create(null), fileByBase=Object.create(null);
  for(const k in files){ fileByPath[norm(k)]=files[k]; fileByBase[base(k)]=files[k]; }
  const pathKeys=Object.keys(fileByPath);
  // a mesh's file: by the path the URDF gives (package://<pkg>/meshes/visual/arm.stl is
  // .../meshes/visual/arm.stl, so a visual and a collision mesh of one name stay apart),
  // else by its bare name
  const resolve=fname=>{
    const raw=String(fname||""), dec=urdfDecode(raw);
    for(const s of dec===raw?[raw]:[raw,dec]){
      const rel=norm(s).replace(/^package:\/\/[^/]+\//,"").replace(/^file:\/\//,"").replace(/^(\.\.?\/)+/,"");
      if(rel in fileByPath) return rel;
      const tail="/"+rel, hit=pathKeys.find(k=>k.endsWith(tail)); if(hit) return hit;
      const b=base(s); if(b in fileByBase) return "#"+b;
    }
    return null;
  };
  // The robot keeps about a million placed triangles (less on a small device), shared
  // out by size: every mesh's count is read from its header first, and each gets the
  // share its placements are of the whole, never under 600. A tyre of 700,000 keeps
  // tens of thousands; a screw of 8 keeps 8.
  // two and a half million unique triangles on a desktop (the app passes a smaller device's own
  // allowance, src/tier.js); copies cost nothing more, since the view draws them as instances
  const total=opts.triangles>0?opts.triangles:2.5e6;
  const placed=new Map(), countOf=new Map();
  for(const l of links) for(const v of urdfKids(l,"visual")){
    const g=urdfKid(v,"geometry"), sh=g&&g.kids[0]; if(!sh||sh.tag!=="mesh") continue;
    const key=resolve(sh.attrs.filename); if(key==null) continue;
    if(!countOf.has(key)){ const f=key[0]==="#"?fileByBase[key.slice(1)]:fileByPath[key]; let n=null; try{ n=urdfMeshCount(base(sh.attrs.filename),f); }catch(e){} countOf.set(key,n); }
    placed.set(key,(placed.get(key)||0)+1);
  }
  // each mesh once, however many copies: the view instances them (src/tessellate.js tessFromSolids)
  let sum=0; for(const [k,n] of countOf) sum+=(n||0);
  const family=new Map();                                  // mesh -> the triangles it keeps
  if(sum>total){
    let pool=[...countOf.keys()].filter(k=>countOf.get(k)!=null), left=total;
    while(pool.length){
      const W=pool.reduce((s,k)=>s+countOf.get(k),0)||1;
      const capped=[];
      for(const k of pool){ const n=countOf.get(k), want=left*n/W, cap=Math.min(n, total*0.3);
        if(want>=cap){ family.set(k,cap); capped.push(k); } }
      if(!capped.length){ for(const k of pool) family.set(k,left*countOf.get(k)/W); break; }
      for(const k of capped) left-=family.get(k);
      pool=pool.filter(k=>!capped.includes(k));
    }
  }
  const meshLinks=Math.max(1,links.filter(l=>urdfKids(l,"visual").some(v=>{ const g=urdfKid(v,"geometry"); return g&&g.kids[0]&&g.kids[0].tag==="mesh"; })).length);
  const budgetOf=key=>{ if(opts.triBudget>0) return opts.triBudget; const n=countOf.get(key);
    if(n==null) return urdfTriBudget(meshLinks,total);                 // a mesh whose count takes a full read (DAE): the even share
    if(sum<=total) return Infinity;
    return Math.max(600,Math.floor(family.get(key)||0)); };
  // each mesh file read once, however many links share it, and cut down to its budget
  const meshCache=new Map(); let triIn=0, triOut=0, cut=0;
  const loadMesh=fname=>{
    const key=resolve(fname), b=base(fname);
    if(key==null) return {miss:b};
    if(meshCache.has(key)) return meshCache.get(key);
    const f=key[0]==="#"?fileByBase[key.slice(1)]:fileByPath[key];
    let r;
    if(!URDF_MESH_EXT.test(b)) r={miss:b+" (only STL, OBJ, glTF, GLB and DAE are read)"};
    else { try{ const t=urdfMesh(b,f,fileByBase);
      if(t&&t.length>=9){ const d=urdfDecimate(t,budgetOf(key)); triIn+=t.length/9; triOut+=d.length/9; if(d.length<t.length) cut++; r={tri:d,key,vol:urdfVolume(t)}; }
      else r={miss:b+" (no triangles in it)"}; }catch(e){ r={miss:b+" ("+(e&&e.message||e)+")"}; } }
    meshCache.set(key,r); return r;
  };
  const kgOf=l=>{ const inertial=urdfKid(l,"inertial"), mass=inertial&&urdfKid(inertial,"mass"); return mass?+mass.attrs.value:NaN; };
  // Onshape's dummy links: a loop's second attachment ("<part>__1__loop_closure"), and
  // the in-between links of a cylindrical or planar mate. None is a part.
  const loopDummy=new Map(), dropped=new Set();
  const shapeless=l=>!urdfKids(l,"visual").length;
  for(const l of links){
    const n=l.attrs.name||""; if(!/_loop_closure$/i.test(n)) continue;
    const stem=n.replace(/_loop_closure$/i,"");
    const cands=[stem, stem.replace(/__\d+_$/,""), stem.replace(/__\d+__\d+$/,""), stem.replace(/_\d+$/,"")];
    const real=cands.find(c=>c!==n&&byName.has(c)&&!/_loop_closure$/i.test(c));
    if(real) loopDummy.set(n,real); else dropped.add(n);
  }
  // a dummy named after the mate itself ("parallel_5_loop_closure": a parallel mate
  // closing a loop) stands for no part the file names: it and its joints are left out
  for(const l of links){ const n=l.attrs.name||""; if(dropped.has(n)) continue;
    if(/_loop_closure(_\d+)?$/i.test(n)&&!loopDummy.has(n)&&shapeless(l)) dropped.add(n); }
  if(dropped.size) notes.push(dropped.size+" loop-closing dumm"+(dropped.size===1?"y":"ies")+" from mates that close a loop onto no named part (a parallel mate's) "+(dropped.size===1?"is":"are")+" left out; the loop is driven through its first joint.");
  const jointsIn=new Map(), jointsOut=new Map();
  for(const j of joints){ const p=(urdfKid(j,"parent")||{attrs:{}}).attrs.link, c=(urdfKid(j,"child")||{attrs:{}}).attrs.link; if(p) (jointsOut.get(p)||jointsOut.set(p,[]).get(p)).push(j); if(c) (jointsIn.get(c)||jointsIn.set(c,[]).get(c)).push(j); }
  // a shapeless, massless link between exactly two moving joints on one axis is a
  // cylindrical mate split in two: one mate, from the outer parent to the final child
  const through=new Map();                               // dummy link -> {outer joint in, joint out}
  for(const l of links){
    const n=l.attrs.name; if(!shapeless(l)||kgOf(l)>1e-4||n===root.attrs.name||loopDummy.has(n)||dropped.has(n)) continue;
    if(!onshape&&!/^cylindrical_\d+(_\d+)*$/i.test(n)) continue;
    if(/^(planar|parallel)_/i.test(n)) continue;
    const ins=jointsIn.get(n)||[], outs=jointsOut.get(n)||[];
    if(ins.length!==1||outs.length!==1) continue;
    const a=ins[0], b=outs[0], ta=a.attrs.type||"fixed", tb=b.attrs.type||"fixed";
    if(ta==="fixed"||tb==="fixed"||!W.has(n)) continue;
    const axA=urdfDir(W.get(n),urdfNums((urdfKid(a,"axis")||{attrs:{}}).attrs.xyz,3,[1,0,0])), axB=urdfDir(W.get((urdfKid(b,"child")||{attrs:{}}).attrs.link)||W.get(n),urdfNums((urdfKid(b,"axis")||{attrs:{}}).attrs.xyz,3,[1,0,0]));
    const la=Math.hypot(...axA)||1, lb=Math.hypot(...axB)||1, dot=(axA[0]*axB[0]+axA[1]*axB[1]+axA[2]*axB[2])/(la*lb);
    if(Math.abs(dot)>0.999&&((ta==="prismatic")!==(tb==="prismatic"))) through.set(n,{a,b});
  }
  // Onshape's planar and parallel mates: chains of dummies (planar_N_M, parallel_N, parallel_N_M)
  // on slides and a turn; the bench holds the part where it was drawn
  const planar=new Set();
  for(const l of links){ const n=l.attrs.name||""; if(/^(planar|parallel)_\d+(_\d+)*$/i.test(n)&&shapeless(l)&&!dropped.has(n)) planar.add(n); }

  const instances=[], occurrences=[], geom={}, idOf=new Map();
  let tinyMass=0, kgEst=0; const tinyNames=[];
  links.forEach((l,i)=>{
    const nm=l.attrs.name||("link"+i);
    if(loopDummy.has(nm)||through.has(nm)||dropped.has(nm)) return;   // not parts: mates, or left out
    const id="L"+i; idOf.set(nm,id);
    const display=onshape?urdfPrettyName(nm):nm, pn=urdfPartNumber(nm);
    let color=null, key=null, tri=null, volOf=null;
    const visuals=urdfKids(l,"visual");
    for(const v of visuals){ const mat=urdfKid(v,"material"); if(mat&&!color){ const c=urdfKid(mat,"color"); color=c?urdfNums(c.attrs.rgba,3,null):(materials[mat.attrs.name]||null); } }
    // Onshape's default appearances are neutral greys: nobody chose them, so the bench's own
    // materials draw the part (aluminium, steel, rubber by what it is), the way a STEP is drawn
    if(color&&Math.abs(color[0]-color[1])<0.04&&Math.abs(color[1]-color[2])<0.04) color=null;
    const one=visuals.length===1?visuals[0]:null, oneG=one&&urdfKid(one,"geometry"), oneShape=oneG&&oneG.kids[0];
    if(oneShape&&oneShape.tag==="mesh"){
      // one mesh, placed one way, in one colour, is one shape however many links wear
      // it: computed once, stored once (a robot package keeps it once too)
      const r=loadMesh(oneShape.attrs.filename);
      if(r.miss){ missingMesh.add(r.miss); tri=new Float32Array(0); }
      else{
        const O=urdfOrigin(one), sc=urdfNums(oneShape.attrs.scale,3,[1,1,1]);
        key=urdfHash(r.key+"|"+sc.join(",")+"|"+O.r.flat().map(x=>x.toFixed(6)).join(",")+"|"+O.t.map(x=>x.toFixed(6)).join(",")+"|"+(color?color.join(","):""));
        const had=geom["URDF/m/MV/e/E"+key+"|default"];
        tri=had?had.parts.P.tri:urdfPlace(r.tri,O,sc);
        volOf=r.vol*Math.abs(sc[0]*sc[1]*sc[2]);
      }
    } else {
      const parts=[]; let total=0;
      for(const v of visuals){
        const O=urdfOrigin(v), g=urdfKid(v,"geometry"), shape=g&&g.kids[0]; if(!shape) continue;
        let T;
        if(shape.tag==="mesh"){ const r=loadMesh(shape.attrs.filename); if(r.miss){ missingMesh.add(r.miss); continue; } T=urdfPlace(r.tri,O,urdfNums(shape.attrs.scale,3,[1,1,1])); }
        else T=urdfPlace(urdfPrim(shape),O,null);
        parts.push(T); total+=T.length;
      }
      tri=new Float32Array(total); let o=0; for(const T of parts){ tri.set(T,o); o+=T.length; }
      if(tri.length) volOf=urdfVolume(tri);
    }
    let kg=kgOf(l), est=false;
    // Onshape gives a part with no material a density of 1 kg/m³, so its "mass" is its
    // volume: that part is weighed from its shape instead, as what its name says it is
    // a closed mesh's volume can't exceed its own box; an open sheet or a broken mesh reads as nothing
    if(volOf!=null&&tri.length){ const bb=[[Infinity,-Infinity],[Infinity,-Infinity],[Infinity,-Infinity]]; for(let k=0;k<tri.length;k+=3) for(let q=0;q<3;q++){ const v=tri[k+q]; if(v<bb[q][0]) bb[q][0]=v; if(v>bb[q][1]) bb[q][1]=v; }
      const box=(bb[0][1]-bb[0][0])*(bb[1][1]-bb[1][0])*(bb[2][1]-bb[2][0]); if(!(volOf<=box*1.001)) volOf=0; }
    const noMaterial=onshape&&Number.isFinite(kg)&&kg>0&&volOf!=null&&(volOf>0?kg/volOf<2:kg<0.1);     // Onshape's 1 kg/m³ placeholder (a sheet: no volume, a tiny mass)
    if(tri.length&&(!Number.isFinite(kg)||kg<=0||noMaterial)){
      if(volOf>1e-9&&(noMaterial||(onshape&&!(kg>0)))){ if(noMaterial){ tinyMass++; if(tinyNames.length<5) tinyNames.push(display); } kg=volOf*urdfDensity(display,pn); est=true; kgEst+=kg; }
      else if(onshape){ kg=0.001; est=true; }                 // a decal, a sticker: a gram
      else kg=NaN;
    }
    const hasKg=Number.isFinite(kg)&&kg>0;
    let eid=key?"E"+key:"E"+i;
    let gk="URDF/m/MV/e/"+eid+"|default";
    if(key&&geom[gk]){ const had=geom[gk].mass.P; if((had?had.kg:null)!==(hasKg?kg:null)){ eid+="m"+urdfHash(String(kg)); gk="URDF/m/MV/e/"+eid+"|default"; } }
    const pid=key?"P":"P"+i;
    if(tri.length&&!geom[gk]) geom[gk]={parts:{[pid]:{name:display,tri,color}}, mass:hasKg?{[pid]:est?{kg,est:true}:{kg}}:{}};
    instances.push({id,name:display,type:"Part",suppressed:false,documentId:"URDF",elementId:eid,configuration:"default",documentMicroversion:"MV",partId:pid,
      partNumber:pn, shapeless:!tri.length});
    if(W.has(nm)) occurrences.push({path:[id],transform:urdfT16(W.get(nm)),fixed:nm===root.attrs.name,hidden:false});
  });
  if(tinyMass) notes.push(tinyMass+" part"+(tinyMass===1?" has":"s have")+" no material in Onshape ("+tinyNames.join(", ")+(tinyMass>5?" …":"")+"), so "+(tinyMass===1?"it's":"they're")+" weighed from "+(tinyMass===1?"its":"their")+" shape"+(tinyMass===1?"":"s")+": about "+kgEst.toFixed(1)+" kg as aluminium, or steel, plastic, rubber or a motor where the name says so. Give them materials for exact masses.");
  if(cut) notes.push(cut+" mesh"+(cut===1?" was":"es were")+" simplified for the browser ("+(triIn/1e6).toFixed(1)+"M triangles in the files, "+(triOut/1e6).toFixed(2)+"M kept; copies share their shape): the shapes draw a little coarser; the joints, placements and masses are exact.");

  // joints as mates: the joint frame, z along its axis, in each end's own frame
  const features=[], limitsOut=[], mimic=[];
  const frameOf=(ax)=>{ const L=Math.hypot(ax[0],ax[1],ax[2])||1, z=ax.map(v=>v/L);
    const x0=Math.abs(z[0])<0.9?[1,0,0]:[0,1,0], d=x0[0]*z[0]+x0[1]*z[1]+x0[2]*z[2];
    let x=[x0[0]-d*z[0],x0[1]-d*z[1],x0[2]-d*z[2]]; const Lx=Math.hypot(x[0],x[1],x[2]); x=x.map(v=>v/Lx);
    const y=[z[1]*x[2]-z[2]*x[1],z[2]*x[0]-z[0]*x[2],z[0]*x[1]-z[1]*x[0]];
    return {r:[[x[0],y[0],z[0]],[x[1],y[1],z[1]],[x[2],y[2],z[2]]],t:[0,0,0]}; };
  const cs=A=>({origin:A.t, xAxis:[A.r[0][0],A.r[1][0],A.r[2][0]], yAxis:[A.r[0][1],A.r[1][1],A.r[2][1]], zAxis:[A.r[0][2],A.r[1][2],A.r[2][2]]});
  const mateOf=t=>t==="revolute"||t==="continuous"?"REVOLUTE":t==="prismatic"?"SLIDER":t==="planar"?"PLANAR":t==="floating"?"BALL":"FASTENED";
  let planarSaid=false;
  const emit=(id,nm,mateType,pLink,cLink,Jw,extra)=>{
    const inWorld=urdfMul(W.get(cLink),Jw), inParent=urdfMul(urdfInv(W.get(pLink)),inWorld);
    features.push({id,suppressed:false,featureType:"mate",featureData:Object.assign({name:nm,mateType,matedEntities:[
      {matedOccurrence:[idOf.get(pLink)],matedCS:cs(inParent)},{matedOccurrence:[idOf.get(cLink)],matedCS:cs(Jw)}]},extra||{})});
  };
  const limitsOf=(j,id,nm,lin)=>{
    const lim=urdfKid(j,"limit"), type=j.attrs.type||"fixed";
    if(lim&&type!=="continuous"&&(lim.attrs.lower!=null||lim.attrs.upper!=null)){
      const lo=+lim.attrs.lower||0, hi=+lim.attrs.upper||0;
      // Onshape writes +-10000 on a slide it has no limits for: that's none
      if(Math.abs(lo)>=1e3&&Math.abs(hi)>=1e3) return;
      const q=v=>lin?(v*1000)+" mm":(v*180/Math.PI)+" deg";
      // named as Onshape's features list names them (src/mates.js applyMateLimits)
      limitsOut.push({message:{featureId:id,name:nm,parameters:[{message:{parameterId:"limitsEnabled",value:true}},
        {message:{parameterId:lin?"limitZMin":"limitAxialZMin",expression:q(lo)}},{message:{parameterId:lin?"limitZMax":"limitAxialZMax",expression:q(hi)}}]}});
    }
  };
  const done=new Set();
  joints.forEach((j,k)=>{
    if(done.has(j)) return;
    const p=(urdfKid(j,"parent")||{attrs:{}}).attrs.link, c=(urdfKid(j,"child")||{attrs:{}}).attrs.link;
    if(!W.has(p)||!W.has(c)||dropped.has(p)||dropped.has(c)) return;
    const type=j.attrs.type||"fixed", id="J"+k, nm=j.attrs.name||id;
    const ax=urdfNums((urdfKid(j,"axis")||{attrs:{}}).attrs.xyz,3,[1,0,0]);
    // a loop closure: the dummy stands for a real part; the mate pins the parent to it
    if(loopDummy.has(c)){
      const real=loopDummy.get(c); if(!idOf.has(p)||!idOf.has(real)||!W.has(real)) return;
      const inWorld=urdfMul(W.get(c),frameOf(ax)), inReal=urdfMul(urdfInv(W.get(real)),inWorld), inParent=urdfMul(urdfInv(W.get(p)),inWorld);
      features.push({id,suppressed:false,featureType:"mate",featureData:{name:"closing_"+nm.replace(/_loop_closure$/i,""),mateType:mateOf(type),matedEntities:[
        {matedOccurrence:[idOf.get(p)],matedCS:cs(inParent)},{matedOccurrence:[idOf.get(real)],matedCS:cs(inReal)}]}});
      return;
    }
    // a slide and a turn through a dummy link: one cylindrical mate
    if(through.has(c)){
      const {b}=through.get(c), c2=(urdfKid(b,"child")||{attrs:{}}).attrs.link; done.add(b);
      if(!idOf.has(p)||!idOf.has(c2)||!W.has(c2)) return;
      const turn=(b.attrs.type||"")==="prismatic"?j:b, axT=urdfNums((urdfKid(turn,"axis")||{attrs:{}}).attrs.xyz,3,[1,0,0]);
      const Jw=frameOf(urdfDir(urdfInv(W.get(c2)),urdfDir(W.get(turn===j?c:c2),axT)));
      const cn=nm.replace(/_\d+$/,""), cont=(turn.attrs.type||"")==="continuous";
      emit(id,cn,"CYLINDRICAL",p,c2,Jw,cont?{continuous:true}:null);
      if(!cont) limitsOf(turn,id,cn,false);
      return;
    }
    if(through.has(p)) return;                              // the second half, already taken
    // Onshape's planar mate: two dummies and three joints; held where it's drawn
    if(planar.has(c)||planar.has(p)){
      if(!idOf.has(p)||!idOf.has(c)) return;
      if(!planarSaid){ planarSaid=true; notes.push("A "+(/^parallel/i.test(nm)?"parallel":"planar")+" mate ("+nm.replace(/(_\d+)+$/,"")+") is held where it was drawn; the bench simulates turns and slides."); }
      emit(id,nm,"FASTENED",p,c,frameOf(ax)); return;
    }
    if(!idOf.has(p)||!idOf.has(c)) return;
    const mateType=mateOf(type);
    emit(id,nm,mateType,p,c,frameOf(ax),type==="continuous"?{continuous:true}:null);
    limitsOf(j,id,nm,mateType==="SLIDER");
    // a mimic joint sits at multiplier * leader + offset (offset in its own m or rad);
    // a multiplier of 0 is a real 0
    const mm=urdfKid(j,"mimic");
    if(mm){ const kk=mm.attrs.multiplier!=null?+mm.attrs.multiplier:1, off=mm.attrs.offset!=null?+mm.attrs.offset:0;
      mimic.push({joint:mm.attrs.joint, id, ratio:Number.isFinite(kk)?kk:1, offset:Number.isFinite(off)?off:0}); }
  });
  const fid=new Map(); features.forEach(f=>fid.set(f.featureData.name,f.id));
  // relationOffset isn't Onshape's: src/mates.js reads it for a URDF's mimic
  for(const r of mimic){ const leader=fid.get(r.joint); if(!leader) continue;
    features.push({id:"R"+r.id,suppressed:false,featureType:"mateRelation",featureData:{name:"mimic "+r.joint,relationType:"LINEAR",mates:[{featureId:leader},{featureId:r.id}],relationRatio:r.ratio,relationOffset:r.offset,reverseDirection:false}}); }
  const asm={rootAssembly:{documentId:"URDF",elementId:"EROOT",configuration:"default",fullConfiguration:"default",documentMicroversion:"MV",instances,occurrences,features,patterns:[]},subAssemblies:[],parts:[]};
  if(missingMesh.size) notes.unshift("Meshes not found with the URDF (drop them together, or drop the whole zip): "+[...missingMesh].slice(0,6).join(", ")+(missingMesh.size>6?" …":""));
  return {format:typeof ONSHAPE_FORMAT==="string"?ONSHAPE_FORMAT:"ftc-simbench.onshape", name:name||robot.attrs.name||"URDF robot", url:"", asm, features:{features:limitsOut}, geom, notes, from:"urdf", onshapeExport:onshape};
}
/* The robot itself */
function cadFromUrdf(text,files,opts){
  const p=urdfToPayload(text,files,opts&&opts.name,opts);
  const cad=cadFromOnshape(p,opts);
  cad.source="urdf";
  if(p.notes.length) cad.onshape.why=p.notes.concat(cad.onshape.why||[]);
  return cad;
}

/* ---- a glTF or GLB on its own: the shapes, with no joints ----
   Onshape's plain glTF export, SolidWorks' "Extended Reality" GLB and the like:
   every mesh node is a part (a part Onshape splits by face is one part again:
   its face meshes hang under one named node), with its colour and name. The
   joints then come from the automatic finder and the editor. */
function gltfToPayload(buf,files,name,opts){
  const meshes=urdfGltfScene(buf,files);
  if(!meshes.length) throw new Error("the glTF has no meshes");
  // the format is Y up; Onshape writes its parts' own Z-up coordinates as they are
  const yUp=!/onshape/i.test(meshes.generator||"");
  const isAuto=n=>/^(mesh|node|primitive)\d*(_mesh)?$/i.test(n||"")||!n;
  const groups=new Map();
  for(const m of meshes){
    // the part's name: the nearest named ancestor that isn't a generated mesh name
    let key=null, label=null;
    for(let i=m.parents.length-1;i>=0;i--){ if(!isAuto(m.parents[i])){ key=m.parents.slice(0,i+1).join("/"); label=m.parents[i]; break; } }
    if(!key){ key="#"+groups.size; label=m.name||"part "+(groups.size+1); }
    const g=groups.get(key)||groups.set(key,{name:label, tri:[], color:null}).get(key);
    const t=m.tri; for(let k=0;k<t.length;k+=3){ if(yUp) g.tri.push(t[k],-t[k+2],t[k+1]); else g.tri.push(t[k],t[k+1],t[k+2]); }
    if(!g.color&&m.color) g.color=m.color;
  }
  // a single part's export names nothing (Onshape writes one node per face, "mesh0",
  // "mesh1"...): that's one part, named after the file
  if([...groups.keys()].every(k=>k[0]==="#")&&groups.size>1){
    const one={name:name||"part", tri:[], color:null};
    for(const g of groups.values()){ for(const v of g.tri) one.tri.push(v); if(!one.color&&g.color) one.color=g.color; }
    groups.clear(); groups.set("#0",one);
  } else if(groups.size===1&&[...groups.keys()][0][0]==="#"&&name) groups.values().next().value.name=name;
  const instances=[], occurrences=[], geom={};
  const budget=urdfTriBudget(groups.size,opts&&opts.triangles);
  let i=0;
  for(const g of groups.values()){
    const id="G"+i, eid="E"+i, key="GLTF/m/MV/e/"+eid+"|default";
    geom[key]={parts:{["P"+i]:{name:g.name, tri:urdfDecimate(g.tri,budget), color:g.color}}, mass:{}};
    instances.push({id,name:g.name,type:"Part",suppressed:false,documentId:"GLTF",elementId:eid,configuration:"default",documentMicroversion:"MV",partId:"P"+i, partNumber:urdfPartNumber(g.name)});
    occurrences.push({path:[id],transform:[1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1],fixed:false,hidden:false});
    i++;
  }
  const asm={rootAssembly:{documentId:"GLTF",elementId:"EROOT",configuration:"default",fullConfiguration:"default",documentMicroversion:"MV",instances,occurrences,features:[],patterns:[]},subAssemblies:[],parts:[]};
  return {format:typeof ONSHAPE_FORMAT==="string"?ONSHAPE_FORMAT:"ftc-simbench.onshape", name:name||"glTF robot", url:"", asm, features:{features:[]}, geom,
    notes:["The shapes come from a glTF, which carries no joints: they're found from the geometry, and the robot check asks about them."+(yUp?" Its Y axis was taken as up, as the format says.":"")], from:"gltf"};
}
