/* ============================================================
   A ROBOT IN A ZIP
   ------------------------------------------------------------
   Onshape's URDF export is a zip (a ROS package: <name>/urdf/<name>.urdf,
   <name>/meshes/*.stl|gltf|glb|obj, a launch file); so is its glTF export,
   and a mentor's onshape-to-robot or ACDC4Robot folder. A team shouldn't
   have to unzip anything: the zip is dropped whole, and what's in it says
   what it is. A file is the one way in that every school network and every
   managed browser allows.

   robotFromZip(bytes) -> {kind, name, ...}:
     simbot  a robot package (src/simbot.js), as the zip itself or inside
     urdf    {text, files} the .urdf and every mesh with it
     mjcf    {text, files} a MuJoCo model and its meshes
     step    {text}        a STEP file
     gltf    {bytes, files, file} shapes only (joints from the finder)
   It refuses what src/simbot.js's zip reader refuses (zip bombs, climbing
   names) and says plainly when there's no robot inside.
   ============================================================ */
// a whole robot's STLs run to a few hundred MB; the reader inflates everything into the tab's memory
const ZIP_ROBOT_CAPS={zipBytes:300e6, unzipped:600e6, files:6000};
const ZIP_MESH_EXT=/\.(stl|obj|gltf|glb|dae|bin|mtl)$/i;

async function robotFromZip(bytes,caps){
  const files=await zipRead(bytes,Object.assign({},ZIP_ROBOT_CAPS,caps||{}));
  const names=[...files.keys()].filter(n=>!/(^|\/)__MACOSX\//.test(n)&&!/(^|\/)\.[^/]*$/.test(n));
  const ext=n=>(/\.([a-z0-9]+)$/i.exec(n)||[,""])[1].toLowerCase();
  const by=e=>names.filter(n=>ext(n)===e);
  const basename=n=>n.replace(/^.*\//,"");
  const dec=u=>new TextDecoder().decode(u);
  const stem=n=>basename(n).replace(/\.[^.]+$/,"");
  // every file a model may name, by its path and by its bare name
  const meshFiles=()=>{ const out={}; for(const n of names) if(ZIP_MESH_EXT.test(n)){ const u=files.get(n); out[n]=u.buffer; out[basename(n)]=u.buffer; } return out; };

  // a robot package: the zip itself, or one inside
  const inside=by("simbot");
  if(inside.length) return {kind:"simbot", name:stem(inside[0]), bytes:files.get(inside[0])};
  if(files.has("manifest.json")&&files.has("joints.json")&&files.has("robot.glb")){
    try{ const m=JSON.parse(dec(files.get("manifest.json"))); if(m&&m.format===SIMBOT_FORMAT) return {kind:"simbot", name:String(m.name||"robot"), bytes:bytes}; }catch(e){}
  }
  // a URDF: Onshape's export puts one under urdf/; take that one, else the biggest
  const urdfs=by("urdf");
  if(urdfs.length){
    const pick=urdfs.find(n=>/(^|\/)urdf\/[^/]+$/.test(n))||urdfs.slice().sort((a,b)=>files.get(b).length-files.get(a).length)[0];
    const text=dec(files.get(pick));
    return {kind:"urdf", name:stem(pick), text, files:meshFiles(), file:pick, onshape:/generated by ONSHAPE/i.test(text.slice(0,400))};
  }
  // a MuJoCo model: .mjcf, or an .xml that opens with <mujoco
  const xmls=by("mjcf").concat(by("xml").filter(n=>{ const u=files.get(n); return /<mujoco[\s>]/.test(dec(u.subarray(0,Math.min(u.length,4096)))); }));
  if(xmls.length){ const pick=xmls.slice().sort((a,b)=>files.get(b).length-files.get(a).length)[0]; return {kind:"mjcf", name:stem(pick), text:dec(files.get(pick)), files:meshFiles(), file:pick}; }
  // a STEP
  const steps=by("step").concat(by("stp"));
  if(steps.length){ const pick=steps.slice().sort((a,b)=>files.get(b).length-files.get(a).length)[0]; return {kind:"step", name:basename(pick), text:dec(files.get(pick)), file:pick}; }
  // shapes only
  const gl=by("glb").concat(by("gltf"));
  if(gl.length){ const pick=gl.slice().sort((a,b)=>files.get(b).length-files.get(a).length)[0]; return {kind:"gltf", name:stem(pick), bytes:files.get(pick), files:meshFiles(), file:pick}; }
  const kinds=[...new Set(names.map(ext).filter(Boolean))].slice(0,8);
  throw new Error("no robot in this zip ("+(kinds.length?"it holds "+kinds.map(k=>"."+k).join(", "):"it's empty")+"). SimBench reads a URDF or MJCF with its meshes, a STEP, a glTF, or a .simbot package.");
}
